In [21]:
!pip install gliner torch pandas openpyxl

Requirement already satisfied: gliner in /usr/local/lib/python3.12/dist-packages (0.2.24)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: transformers>=4.57.3 in /usr/local/lib/python3.12/dist-packages (from gliner) (5.0.0)
Requirement already satisfied: huggingface_hub>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from gliner) (1.3.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gliner) (4.67.1)
Requirement already satisfied: onnxruntime in /usr/local/lib/python3.12/dist-packages (from gliner) (1.23.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from gliner) (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (0.21.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.3->gliner) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.3->gliner) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.3->gliner) (0.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (5.29.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (0.16.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.12/dist-packages (from coloredlogs->onnxruntime->gliner) (10.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub>=0.21.4->gliner) (8.3.1)

In [22]:
import torch
import pandas as pd
from gliner import GLiNER
from typing import List, Dict

In [23]:
DATA_PATH = "/content/sample_data/trump_tweets_sota_classified(1).xlsx"

df = pd.read_excel(DATA_PATH)

print("Columns:", df.columns.tolist())
print("Total rows:", len(df))

Columns: ['tweet_id', 'tweet_text', 'date', 'primary_asset_class', 'primary_token', 'primary_ticker', 'sentiment', 'sentiment_score', 'event_types', 'entities', 'signal_direction', 'signal_strength', 'confidence', 'latency_ms', 'layers_used']
Total rows: 255

In [24]:
df[["tweet_id", "tweet_text"]].head()

       tweet_id                      tweet_text
0  f6b6bc55c8b5  washingtonexaminer.com/restori
1  362a7010b3c1  breitbart.com/politics/2025/06
2  65c19d0b7fb5  redstate.com/redstate-guest-ed
3  8f0d572a979f  foxnews.com/opinion/loeffler-t
4  707c1b8d12dd  nypost.com/2025/06/28/us-news/

In [25]:
df["tweet_text"] = df["tweet_text"].astype(str).str.strip()
df = df[df["tweet_text"] != ""]

In [61]:
model = GLiNER.from_pretrained("urchade/gliner_base")

model.eval()  # 🔴 CRITICAL
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

print(f"Model loaded on {device}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:186: UserWarning: The `resume_download` argument is deprecated and ignored in `snapshot_download`. Downloads always resume whenever possible.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Model loaded on cpu

In [63]:
NER_LABELS = [
    "person name like Putin or Biden",
    "country name like Ukraine or China",
    "organization name like Fed or OPEC",
    "commodity name like oil or gold",
    "currency name like dollar or euro"
]

In [71]:
import re

def clean_tweet(text: str) -> str:
    """Clean tweet text for better NER performance."""
    if not isinstance(text, str):
        return ""
    # Remove URLs (including bare domains like example.com/path)
    text = re.sub(r'https?://\S+', '', text)  # http:// or https://
    text = re.sub(r'www\.\S+', '', text)       # www.
    text = re.sub(r'\S+\.(com|org|net|gov|io|co|edu|info|biz|me)/\S*', '', text)  # bare domains with path
    text = re.sub(r'\S+\.(com|org|net|gov|io|co|edu|info|biz|me)\b', '', text)    # bare domains without path
    # Remove mentions but keep the name
    text = re.sub(r'@(\w+)', r'\1', text)
    # Remove hashtag symbol but keep the word
    text = re.sub(r'#(\w+)', r'\1', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def is_valid_tweet(text: str) -> bool:
    """Check if tweet has meaningful text content (not just a URL)."""
    if not isinstance(text, str):
        return False
    cleaned = clean_tweet(text)
    # Must have at least 10 chars of actual content after cleaning
    return len(cleaned) >= 10

def extract_entities(
    text: str,
    labels=NER_LABELS,
    threshold: float = 0.05
):
    if not isinstance(text, str) or not text.strip():
        return []

    entities = model.predict_entities(
        text=text,
        labels=labels,
        threshold=threshold,
        flat_ner=True  # Re-adding flat_ner=True for granular entities
    )

    # Debugging: Print raw predictions before filtering
    print(f"Raw predictions for '{text}': {entities}")

    return [
        {
            "entity": e["text"],
            "label": e["label"],
            "score": round(e["score"], 3)
        }
        for e in entities
    ]

In [72]:
# Check how many tweets are just URLs vs actual text
url_only_count = sum(1 for t in df["tweet_text"] if not is_valid_tweet(t))
valid_count = sum(1 for t in df["tweet_text"] if is_valid_tweet(t))

print(f"Total tweets: {len(df)}")
print(f"URL-only tweets (skipped): {url_only_count}")
print(f"Valid text tweets: {valid_count}")
print(f"\nExamples of URL-only tweets:")
for i, t in enumerate(df["tweet_text"]):
    if not is_valid_tweet(t):
        print(f"  - {str(t)[:60]}")
        if i > 4:
            break

Total tweets: 255
URL-only tweets (skipped): 50
Valid text tweets: 205

Examples of URL-only tweets:
  - washingtonexaminer.com/restori
  - breitbart.com/politics/2025/06
  - redstate.com/redstate-guest-ed
  - foxnews.com/opinion/loeffler-t
  - nypost.com/2025/06/28/us-news/
  - whitehouse.gov/articles/2025/0

In [74]:
# Find a good sample tweet with actual text content
print("Examples of valid tweets with text content:\n")
for i, row in df.iterrows():
    text = row["tweet_text"]
    if is_valid_tweet(text):
        cleaned = clean_tweet(text)
        print(f"Tweet {i}:")
        print(f"  Original: {text[:100]}...")
        print(f"  Cleaned:  {cleaned[:100]}...")
        entities = extract_entities(text)
        if entities:
            print(f"  Entities:")
            for e in entities:
                print(f"    → {e['label']}: {e['entity']} ({e['score']})")
        else:
            print("  Entities: None found")
        print()
        if i > 15:  # Show first few valid examples
            break

Examples of valid tweets with text content:

Tweet 5:
  Original: I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act togeth...
  Cleaned:  I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act togeth...
Raw predictions for 'I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act together. Please pass along the word to the tens of thousands of people who are there. We may have to resc...': [{'start': 37, 'end': 72, 'text': 'Faith Leaders Conference Call. AT&T', 'label': 'commodity name like oil or gold', 'score': 0.08294535428285599}, {'start': 159, 'end': 201, 'text': 'people who are there. We may have to resc.', 'label': 'country name like Ukraine or China', 'score': 0.07102049887180328}]
  Entities:
    → commodity name like oil or gold: Faith Leaders Conference Call. AT&T (0.083)
    → country name like Ukraine or China: people who are there. We may have to resc. (0.071)

Tweet 6:
  Original: I’m doing a major Conference Call with Faith Leaders from all over the Country, and AT&T is totally ...
  Cleaned:  I’m doing a major Conference Call with Faith Leaders from all over the Country, and AT&T is totally ...
Raw predictions for 'I’m doing a major Conference Call with Faith Leaders from all over the Country, and AT&T is totally unable to make their equipment work properly. This is the second time it’s happened. If the Boss of ...': [{'start': 18, 'end': 52, 'text': 'Conference Call with Faith Leaders', 'label': 'commodity name like oil or gold', 'score': 0.1009126603603363}, {'start': 84, 'end': 88, 'text': 'AT&T', 'label': 'organization name like Fed or OPEC', 'score': 0.11035725474357605}, {'start': 158, 'end': 196, 'text': 'second time it’s happened. If the Boss', 'label': 'person name like Putin or Biden', 'score': 0.13016793131828308}]
  Entities:
    → commodity name like oil or gold: Conference Call with Faith Leaders (0.101)
    → organization name like Fed or OPEC: AT&T (0.11)
    → person name like Putin or Biden: second time it’s happened. If the Boss (0.13)

Tweet 7:
  Original: To show people how spoiled Countries have become with respect to the United States of America, and I...
  Cleaned:  To show people how spoiled Countries have become with respect to the United States of America, and I...
Raw predictions for 'To show people how spoiled Countries have become with respect to the United States of America, and I have great respect for Japan, they won’t take our RICE, and yet they have a massive rice shortage. ...': [{'start': 27, 'end': 93, 'text': 'Countries have become with respect to the United States of America', 'label': 'commodity name like oil or gold', 'score': 0.10972268134355545}, {'start': 124, 'end': 129, 'text': 'Japan', 'label': 'country name like Ukraine or China', 'score': 0.06904712319374084}, {'start': 151, 'end': 198, 'text': 'RICE, and yet they have a massive rice shortage', 'label': 'person name like Putin or Biden', 'score': 0.2181246429681778}]
  Entities:
    → commodity name like oil or gold: Countries have become with respect to the United States of America (0.11)
    → country name like Ukraine or China: Japan (0.069)
    → person name like Putin or Biden: RICE, and yet they have a massive rice shortage (0.218)

Tweet 9:
  Original: Jerome “Too Late” Powell, and his entire Board, should be ashamed of themselves for allowing this to...
  Cleaned:  Jerome “Too Late” Powell, and his entire Board, should be ashamed of themselves for allowing this to...
Raw predictions for 'Jerome “Too Late” Powell, and his entire Board, should be ashamed of themselves for allowing this to happen to the United States. They have one of the easiest, yet most prestigious, jobs in America, a...': [{'start': 41, 'end': 46, 'text': 'Board', 'label': 'commodity name like oil or gold', 'score': 0.055223751813173294}, {'start': 58, 'end': 128, 'text': 'ashamed of themselves for allowing this to happen to the United States', 'label': 'commodity name like oil or gold', 'score': 0.07000846415758133}, {'start': 140, 'end': 197, 'text': 'one of the easiest, yet most prestigious, jobs in America', 'label': 'organization name like Fed or OPEC', 'score': 0.09173663705587387}]
  Entities:
    → commodity name like oil or gold: Board (0.055)
    → commodity name like oil or gold: ashamed of themselves for allowing this to happen to the United States (0.07)
    → organization name like Fed or OPEC: one of the easiest, yet most prestigious, jobs in America (0.092)

Tweet 10:
  Original: Not that it really matters, but a terribly untalented writer for badly failing Forbes Magazine, Dan ...
  Cleaned:  Not that it really matters, but a terribly untalented writer for badly failing Forbes Magazine, Dan ...
Raw predictions for 'Not that it really matters, but a terribly untalented writer for badly failing Forbes Magazine, Dan Alexander, who probably can’t get a meaningful job in the business, has written so inaccurately abou...': [{'start': 79, 'end': 94, 'text': 'Forbes Magazine', 'label': 'commodity name like oil or gold', 'score': 0.057326819747686386}, {'start': 96, 'end': 150, 'text': 'Dan Alexander, who probably can’t get a meaningful job', 'label': 'organization name like Fed or OPEC', 'score': 0.07261627912521362}, {'start': 158, 'end': 203, 'text': 'business, has written so inaccurately abou...', 'label': 'person name like Putin or Biden', 'score': 0.06221792474389076}]
  Entities:
    → commodity name like oil or gold: Forbes Magazine (0.057)
    → organization name like Fed or OPEC: Dan Alexander, who probably can’t get a meaningful job (0.073)
    → person name like Putin or Biden: business, has written so inaccurately abou... (0.062)

Tweet 11:
  Original: Tell phony Democrat Senator Chris Coons that I am not offering Iran ANYTHING, unlike Obama, who paid...
  Cleaned:  Tell phony Democrat Senator Chris Coons that I am not offering Iran ANYTHING, unlike Obama, who paid...
Raw predictions for 'Tell phony Democrat Senator Chris Coons that I am not offering Iran ANYTHING, unlike Obama, who paid them $Billions under the stupid “road to a Nuclear Weapon JCPOA (which would now be expired!), nor ...': [{'start': 144, 'end': 194, 'text': 'Nuclear Weapon JCPOA (which would now be expired!)', 'label': 'person name like Putin or Biden', 'score': 0.12585434317588806}]
  Entities:
    → person name like Putin or Biden: Nuclear Weapon JCPOA (which would now be expired!) (0.126)

Tweet 12:
  Original: The Trump Administration has gotten costs down, very substantially, for the American Consumer. There...
  Cleaned:  The Trump Administration has gotten costs down, very substantially, for the American Consumer. There...
Raw predictions for 'The Trump Administration has gotten costs down, very substantially, for the American Consumer. There has never been anything like this!': [{'start': 0, 'end': 24, 'text': 'The Trump Administration', 'label': 'commodity name like oil or gold', 'score': 0.054753586649894714}, {'start': 76, 'end': 134, 'text': 'American Consumer. There has never been anything like this', 'label': 'person name like Putin or Biden', 'score': 0.14229048788547516}]
  Entities:
    → commodity name like oil or gold: The Trump Administration (0.055)
    → person name like Putin or Biden: American Consumer. There has never been anything like this (0.142)

Tweet 13:
  Original: ONE GREAT BIG BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN!...
  Cleaned:  ONE GREAT BIG BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN!...
Raw predictions for 'ONE GREAT BIG BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN!': [{'start': 14, 'end': 78, 'text': 'BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN', 'label': 'person name like Putin or Biden', 'score': 0.08888700604438782}]
  Entities:
    → person name like Putin or Biden: BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN (0.089)

Tweet 15:
  Original: For all cost cutting Republicans, of which I am one, REMEMBER, you still have to get reelected. Don’...
  Cleaned:  For all cost cutting Republicans, of which I am one, REMEMBER, you still have to get reelected. Don’...
Raw predictions for 'For all cost cutting Republicans, of which I am one, REMEMBER, you still have to get reelected. Don’t go too crazy! We will make it all up, times 10, with GROWTH, more than ever before': [{'start': 21, 'end': 32, 'text': 'Republicans', 'label': 'organization name like Fed or OPEC', 'score': 0.09662801772356033}, {'start': 53, 'end': 94, 'text': 'REMEMBER, you still have to get reelected', 'label': 'organization name like Fed or OPEC', 'score': 0.05170482024550438}, {'start': 116, 'end': 161, 'text': 'We will make it all up, times 10, with GROWTH', 'label': 'person name like Putin or Biden', 'score': 0.12633676826953888}]
  Entities:
    → organization name like Fed or OPEC: Republicans (0.097)
    → organization name like Fed or OPEC: REMEMBER, you still have to get reelected (0.052)
    → person name like Putin or Biden: We will make it all up, times 10, with GROWTH (0.126)

Tweet 16:
  Original: Great News! “Senator” Thom Tillis will not be seeking reelection....
  Cleaned:  Great News! “Senator” Thom Tillis will not be seeking reelection....
Raw predictions for 'Great News! “Senator” Thom Tillis will not be seeking reelection.': [{'start': 13, 'end': 65, 'text': 'Senator” Thom Tillis will not be seeking reelection.', 'label': 'person name like Putin or Biden', 'score': 0.1622769683599472}]
  Entities:
    → person name like Putin or Biden: Senator” Thom Tillis will not be seeking reelection. (0.162)

In [75]:
test_text = "Oil prices are high. Putin spoke about Ukraine. Dollar is strong."

print(f"Testing general text: {test_text}")
results_general_text = extract_entities(test_text)
if results_general_text:
    print("Found entities:")
    for entity in results_general_text:
        print(f"  - {entity['label']}: {entity['entity']} (Score: {entity['score']})")
else:
    print("No entities found for this general text.")

Testing general text: Oil prices are high. Putin spoke about Ukraine. Dollar is strong.
Raw predictions for 'Oil prices are high. Putin spoke about Ukraine. Dollar is strong.': [{'start': 0, 'end': 54, 'text': 'Oil prices are high. Putin spoke about Ukraine. Dollar', 'label': 'person name like Putin or Biden', 'score': 0.0978536531329155}]
Found entities:
  - person name like Putin or Biden: Oil prices are high. Putin spoke about Ukraine. Dollar (Score: 0.098)

In [76]:
specific_tweet_text = "I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act together."
print(f"Testing tweet with very low threshold (0.1): {specific_tweet_text}")
results_low_threshold = extract_entities(specific_tweet_text, threshold=0.1)
if results_low_threshold:
    print("Found entities with 0.1 threshold:")
    for entity in results_low_threshold:
        print(f"  - {entity['label']}: {entity['entity']} (Score: {entity['score']})")
else:
    print("No entities found even with 0.1 threshold for this specific tweet.")

Testing tweet with very low threshold (0.1): I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act together.
Raw predictions for 'I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act together.': [{'start': 37, 'end': 72, 'text': 'Faith Leaders Conference Call. AT&T', 'label': 'country name like Ukraine or China', 'score': 0.1590319126844406}]
Found entities with 0.1 threshold:
  - country name like Ukraine or China: Faith Leaders Conference Call. AT&T (Score: 0.159)

In [79]:
sample = df.loc[0, "tweet_text"]
sample

'washingtonexaminer.com/restori'

In [80]:
extract_entities(sample)

Raw predictions for 'washingtonexaminer.com/restori': [{'start': 0, 'end': 30, 'text': 'washingtonexaminer.com/restori', 'label': 'commodity name like oil or gold', 'score': 0.13208290934562683}]

[{'entity': 'washingtonexaminer.com/restori',
  'label': 'commodity name like oil or gold',
  'score': 0.132}]

In [81]:
df["entities"] = df["tweet_text"].apply(extract_entities)

Raw predictions for 'washingtonexaminer.com/restori': [{'start': 0, 'end': 30, 'text': 'washingtonexaminer.com/restori', 'label': 'commodity name like oil or gold', 'score': 0.13208290934562683}]
Raw predictions for 'breitbart.com/politics/2025/06': [{'start': 0, 'end': 30, 'text': 'breitbart.com/politics/2025/06', 'label': 'person name like Putin or Biden', 'score': 0.13495050370693207}]
Raw predictions for 'redstate.com/redstate-guest-ed': [{'start': 0, 'end': 30, 'text': 'redstate.com/redstate-guest-ed', 'label': 'commodity name like oil or gold', 'score': 0.13462543487548828}]
Raw predictions for 'foxnews.com/opinion/loeffler-t': [{'start': 0, 'end': 30, 'text': 'foxnews.com/opinion/loeffler-t', 'label': 'person name like Putin or Biden', 'score': 0.11655747890472412}]
Raw predictions for 'nypost.com/2025/06/28/us-news/': [{'start': 0, 'end': 30, 'text': 'nypost.com/2025/06/28/us-news/', 'label': 'person name like Putin or Biden', 'score': 0.13180170953273773}]
Raw predictions for 'I apologize for the long wait on the Faith Leaders Conference Call. AT&T ought to get its act together. Please pass along the word to the tens of thousands of people who are there. We may have to resc...': [{'start': 37, 'end': 72, 'text': 'Faith Leaders Conference Call. AT&T', 'label': 'commodity name like oil or gold', 'score': 0.08294535428285599}, {'start': 159, 'end': 201, 'text': 'people who are there. We may have to resc.', 'label': 'country name like Ukraine or China', 'score': 0.07102049887180328}]
Raw predictions for 'I’m doing a major Conference Call with Faith Leaders from all over the Country, and AT&T is totally unable to make their equipment work properly. This is the second time it’s happened. If the Boss of ...': [{'start': 18, 'end': 52, 'text': 'Conference Call with Faith Leaders', 'label': 'commodity name like oil or gold', 'score': 0.1009126603603363}, {'start': 84, 'end': 88, 'text': 'AT&T', 'label': 'organization name like Fed or OPEC', 'score': 0.11035725474357605}, {'start': 158, 'end': 196, 'text': 'second time it’s happened. If the Boss', 'label': 'person name like Putin or Biden', 'score': 0.13016793131828308}]
Raw predictions for 'To show people how spoiled Countries have become with respect to the United States of America, and I have great respect for Japan, they won’t take our RICE, and yet they have a massive rice shortage. ...': [{'start': 27, 'end': 93, 'text': 'Countries have become with respect to the United States of America', 'label': 'commodity name like oil or gold', 'score': 0.10972268134355545}, {'start': 124, 'end': 129, 'text': 'Japan', 'label': 'country name like Ukraine or China', 'score': 0.06904712319374084}, {'start': 151, 'end': 198, 'text': 'RICE, and yet they have a massive rice shortage', 'label': 'person name like Putin or Biden', 'score': 0.2181246429681778}]
Raw predictions for 'whitehouse.gov/articles/2025/0': [{'start': 0, 'end': 30, 'text': 'whitehouse.gov/articles/2025/0', 'label': 'person name like Putin or Biden', 'score': 0.29842662811279297}]
Raw predictions for 'Jerome “Too Late” Powell, and his entire Board, should be ashamed of themselves for allowing this to happen to the United States. They have one of the easiest, yet most prestigious, jobs in America, a...': [{'start': 41, 'end': 46, 'text': 'Board', 'label': 'commodity name like oil or gold', 'score': 0.055223751813173294}, {'start': 58, 'end': 128, 'text': 'ashamed of themselves for allowing this to happen to the United States', 'label': 'commodity name like oil or gold', 'score': 0.07000846415758133}, {'start': 140, 'end': 197, 'text': 'one of the easiest, yet most prestigious, jobs in America', 'label': 'organization name like Fed or OPEC', 'score': 0.09173663705587387}]
Raw predictions for 'Not that it really matters, but a terribly untalented writer for badly failing Forbes Magazine, Dan Alexander, who probably can’t get a meaningful job in the business, has written so inaccurately abou...': [{'start': 79, 'end': 94, 'text': 'Forbes Magazine', 'label': 'commodity name like oil or gold', 'score': 0.057326819747686386}, {'start': 96, 'end': 150, 'text': 'Dan Alexander, who probably can’t get a meaningful job', 'label': 'organization name like Fed or OPEC', 'score': 0.07261627912521362}, {'start': 158, 'end': 203, 'text': 'business, has written so inaccurately abou...', 'label': 'person name like Putin or Biden', 'score': 0.06221792474389076}]
Raw predictions for 'Tell phony Democrat Senator Chris Coons that I am not offering Iran ANYTHING, unlike Obama, who paid them $Billions under the stupid “road to a Nuclear Weapon JCPOA (which would now be expired!), nor ...': [{'start': 144, 'end': 194, 'text': 'Nuclear Weapon JCPOA (which would now be expired!)', 'label': 'person name like Putin or Biden', 'score': 0.12585434317588806}]
Raw predictions for 'The Trump Administration has gotten costs down, very substantially, for the American Consumer. There has never been anything like this!': [{'start': 0, 'end': 24, 'text': 'The Trump Administration', 'label': 'commodity name like oil or gold', 'score': 0.054753586649894714}, {'start': 76, 'end': 134, 'text': 'American Consumer. There has never been anything like this', 'label': 'person name like Putin or Biden', 'score': 0.14229048788547516}]
Raw predictions for 'ONE GREAT BIG BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN!': [{'start': 14, 'end': 78, 'text': 'BEAUTIFUL BILL, is moving along nicely! MAKE AMERICA GREAT AGAIN', 'label': 'person name like Putin or Biden', 'score': 0.08888700604438782}]
Raw predictions for 'rumble.com/v6vf0gv-real-americ': []
Raw predictions for 'For all cost cutting Republicans, of which I am one, REMEMBER, you still have to get reelected. Don’t go too crazy! We will make it all up, times 10, with GROWTH, more than ever before': [{'start': 21, 'end': 32, 'text': 'Republicans', 'label': 'organization name like Fed or OPEC', 'score': 0.09662801772356033}, {'start': 53, 'end': 94, 'text': 'REMEMBER, you still have to get reelected', 'label': 'organization name like Fed or OPEC', 'score': 0.05170482024550438}, {'start': 116, 'end': 161, 'text': 'We will make it all up, times 10, with GROWTH', 'label': 'person name like Putin or Biden', 'score': 0.12633676826953888}]
Raw predictions for 'Great News! “Senator” Thom Tillis will not be seeking reelection.': [{'start': 13, 'end': 65, 'text': 'Senator” Thom Tillis will not be seeking reelection.', 'label': 'person name like Putin or Biden', 'score': 0.1622769683599472}]
Raw predictions for 'Great Congressman Greg Steube is 100% correct. An unelected Senate Staffer (Parliamentarian), should not be allowed to hurt the Republicans Bill. Wants many fantastic things out. NO! DJT': [{'start': 23, 'end': 74, 'text': 'Steube is 100% correct. An unelected Senate Staffer', 'label': 'commodity name like oil or gold', 'score': 0.05458177998661995}, {'start': 76, 'end': 139, 'text': 'Parliamentarian), should not be allowed to hurt the Republicans', 'label': 'organization name like Fed or OPEC', 'score': 0.16366109251976013}, {'start': 140, 'end': 186, 'text': 'Bill. Wants many fantastic things out. NO! DJT', 'label': 'person name like Putin or Biden', 'score': 0.3288911283016205}]
Raw predictions for 'breitbart.com/clips/2025/06/29': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/29', 'label': 'person name like Putin or Biden', 'score': 0.22616933286190033}]
Raw predictions for 'breitbart.com/clips/2025/06/30': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/30', 'label': 'person name like Putin or Biden', 'score': 0.23677565157413483}]
Raw predictions for 'breitbart.com/clips/2025/06/31': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/31', 'label': 'person name like Putin or Biden', 'score': 0.18748606741428375}]
Raw predictions for 'breitbart.com/clips/2025/06/32': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/32', 'label': 'person name like Putin or Biden', 'score': 0.2415933758020401}]
Raw predictions for 'breitbart.com/clips/2025/06/33': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/33', 'label': 'person name like Putin or Biden', 'score': 0.34221285581588745}]
Raw predictions for 'breitbart.com/clips/2025/06/34': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/34', 'label': 'person name like Putin or Biden', 'score': 0.23642578721046448}]
Raw predictions for 'breitbart.com/clips/2025/06/35': [{'start': 0, 'end': 30, 'text': 'breitbart.com/clips/2025/06/35', 'label': 'person name like Putin or Biden', 'score': 0.34016528725624084}]
Raw predictions for 'This is such a BIG DAY—A very MONUMENTAL decision!': [{'start': 0, 'end': 50, 'text': 'This is such a BIG DAY—A very MONUMENTAL decision!', 'label': 'person name like Putin or Biden', 'score': 0.21239757537841797}]
Raw predictions for 'John Yoo: "This is a REALLY BIG WIN for the presidency…because what the court has also respected here is that the President is elected by the American people to carry out an agenda, and it's important...': [{'start': 0, 'end': 35, 'text': 'John Yoo: "This is a REALLY BIG WIN', 'label': 'commodity name like oil or gold', 'score': 0.05257922410964966}, {'start': 114, 'end': 157, 'text': 'President is elected by the American people', 'label': 'country name like Ukraine or China', 'score': 0.0710812583565712}, {'start': 174, 'end': 203, 'text': "agenda, and it's important...", 'label': 'country name like Ukraine or China', 'score': 0.2112116813659668}]
Raw predictions for 'After many years of decline in our air traffic control system, the One Big Beautiful Bill will modernize this decrepit relic and give America the best, most advanced air traffic control system on Eart...': [{'start': 35, 'end': 89, 'text': 'air traffic control system, the One Big Beautiful Bill', 'label': 'commodity name like oil or gold', 'score': 0.052195653319358826}, {'start': 134, 'end': 200, 'text': 'America the best, most advanced air traffic control system on Eart', 'label': 'organization name like Fed or OPEC', 'score': 0.1769309639930725}]
Raw predictions for 'The Great Republicans in the U.S. Senate are working all weekend to finish our “ONE, BIG, BEAUTIFUL BILL.” We are on the precipice of delivering Massive General Tax Cuts, NO TAX ON TIPS, NO TAX ON OVE...': [{'start': 10, 'end': 21, 'text': 'Republicans', 'label': 'commodity name like oil or gold', 'score': 0.08879123628139496}, {'start': 29, 'end': 40, 'text': 'U.S. Senate', 'label': 'commodity name like oil or gold', 'score': 0.08193660527467728}, {'start': 100, 'end': 160, 'text': 'BILL.” We are on the precipice of delivering Massive General', 'label': 'country name like Ukraine or China', 'score': 0.06750618666410446}, {'start': 161, 'end': 185, 'text': 'Tax Cuts, NO TAX ON TIPS', 'label': 'country name like Ukraine or China', 'score': 0.08105461299419403}, {'start': 190, 'end': 203, 'text': 'TAX ON OVE...', 'label': 'commodity name like oil or gold', 'score': 0.05071214959025383}]
Raw predictions for 'We have just been informed that Canada, a very difficult Country to TRADE with, including the fact that they have charged our Farmers as much as 400% Tariffs, for years, on Dairy Products, has just an...': [{'start': 32, 'end': 38, 'text': 'Canada', 'label': 'country name like Ukraine or China', 'score': 0.07767964154481888}, {'start': 57, 'end': 73, 'text': 'Country to TRADE', 'label': 'commodity name like oil or gold', 'score': 0.09287339448928833}, {'start': 126, 'end': 133, 'text': 'Farmers', 'label': 'country name like Ukraine or China', 'score': 0.06425657868385315}, {'start': 150, 'end': 187, 'text': 'Tariffs, for years, on Dairy Products', 'label': 'country name like Ukraine or China', 'score': 0.1541425734758377}]
Raw predictions for 'Why would the so-called “Supreme Leader,” Ayatollah Ali Khamenei, of the war torn Country of Iran, say so blatantly and foolishly that he won the War with Israel, when he knows his statement is a lie,...': [{'start': 0, 'end': 64, 'text': 'Why would the so-called “Supreme Leader,” Ayatollah Ali Khamenei', 'label': 'commodity name like oil or gold', 'score': 0.05420029163360596}, {'start': 82, 'end': 97, 'text': 'Country of Iran', 'label': 'commodity name like oil or gold', 'score': 0.0652046725153923}, {'start': 146, 'end': 199, 'text': 'War with Israel, when he knows his statement is a lie', 'label': 'organization name like Fed or OPEC', 'score': 0.1902397722005844}]
Raw predictions for 'Jonathan Turley: "Here the Supreme Court is agreeing with the Trump Administration that these judges are well past their authority."': [{'start': 0, 'end': 40, 'text': 'Jonathan Turley: "Here the Supreme Court', 'label': 'commodity name like oil or gold', 'score': 0.09221305698156357}, {'start': 62, 'end': 132, 'text': 'Trump Administration that these judges are well past their authority."', 'label': 'person name like Putin or Biden', 'score': 0.28023380041122437}]
Raw predictions for 'This morning, the Supreme Court has delivered a monumental victory for the Constitution…': [{'start': 0, 'end': 12, 'text': 'This morning', 'label': 'commodity name like oil or gold', 'score': 0.07647629082202911}, {'start': 18, 'end': 87, 'text': 'Supreme Court has delivered a monumental victory for the Constitution', 'label': 'commodity name like oil or gold', 'score': 0.29525911808013916}]
Raw predictions for 'GIANT WIN in the United States Supreme Court! Even the Birthright Citizenship Hoax has been, indirectly, hit hard. It had to do with the babies of slaves (same year!), not the SCAMMING of our Immigrat...': [{'start': 17, 'end': 82, 'text': 'United States Supreme Court! Even the Birthright Citizenship Hoax', 'label': 'commodity name like oil or gold', 'score': 0.07340118288993835}, {'start': 105, 'end': 153, 'text': 'hit hard. It had to do with the babies of slaves', 'label': 'commodity name like oil or gold', 'score': 0.0988990068435669}, {'start': 155, 'end': 200, 'text': 'same year!), not the SCAMMING of our Immigrat', 'label': 'person name like Putin or Biden', 'score': 0.19214753806591034}]
Raw predictions for 'rsbnetwork.com/news/gop-congre': [{'start': 0, 'end': 30, 'text': 'rsbnetwork.com/news/gop-congre', 'label': 'commodity name like oil or gold', 'score': 0.059990014880895615}]
Raw predictions for 'The One Big Beautiful Bill will Secure our Borders, turbocharge our economy, and bring back the American Dream. This is the ultimate codification of our agenda to very simply Make America Great Again!': [{'start': 22, 'end': 50, 'text': 'Bill will Secure our Borders', 'label': 'organization name like Fed or OPEC', 'score': 0.059698622673749924}, {'start': 96, 'end': 159, 'text': 'American Dream. This is the ultimate codification of our agenda', 'label': 'person name like Putin or Biden', 'score': 0.06229846552014351}]
Raw predictions for 'Tom Homan: “The Big Beautiful Bill should be nonpartisan...if we get this bill passed, we got more agents on the road, we buy more beds, we get more transportation flights—More agents means more bad g...': [{'start': 30, 'end': 78, 'text': 'Bill should be nonpartisan...if we get this bill', 'label': 'commodity name like oil or gold', 'score': 0.05357734113931656}, {'start': 149, 'end': 203, 'text': 'transportation flights—More agents means more bad g...', 'label': 'person name like Putin or Biden', 'score': 0.14459459483623505}]
Raw predictions for 'The One Big Beautiful Bill is also an incredible victory for America's Great Farmers…': [{'start': 22, 'end': 84, 'text': "Bill is also an incredible victory for America's Great Farmers", 'label': 'person name like Putin or Biden', 'score': 0.2461281418800354}]
Raw predictions for 'The One Big Beautiful Bill will be the single most important piece of Border Legislation ever to cross the floor of Congress…': [{'start': 22, 'end': 26, 'text': 'Bill', 'label': 'commodity name like oil or gold', 'score': 0.0560237355530262}, {'start': 70, 'end': 124, 'text': 'Border Legislation ever to cross the floor of Congress', 'label': 'commodity name like oil or gold', 'score': 0.18586455285549164}]
Raw predictions for 'youtube.com/live/xa20sWp9bWA?s': [{'start': 0, 'end': 28, 'text': 'youtube.com/live/xa20sWp9bWA', 'label': 'commodity name like oil or gold', 'score': 0.06618370860815048}]
Raw predictions for 'The Democrats are the ones who leaked the information on the PERFECT FLIGHT to the Nuclear Sites in Iran. They should be prosecuted!': [{'start': 4, 'end': 13, 'text': 'Democrats', 'label': 'commodity name like oil or gold', 'score': 0.07529153674840927}, {'start': 69, 'end': 131, 'text': 'FLIGHT to the Nuclear Sites in Iran. They should be prosecuted', 'label': 'person name like Putin or Biden', 'score': 0.11818621307611465}]
Raw predictions for 'thestreet.com/economy/fannie-m': [{'start': 0, 'end': 30, 'text': 'thestreet.com/economy/fannie-m', 'label': 'person name like Putin or Biden', 'score': 0.15972979366779327}]
Raw predictions for '“Rand Paul broke with his own party on border security funding. Then his party broke with him.” politico.com/news/2025/06/20/r': [{'start': 6, 'end': 10, 'text': 'Paul', 'label': 'commodity name like oil or gold', 'score': 0.06550206243991852}, {'start': 104, 'end': 126, 'text': '.com/news/2025/06/20/r', 'label': 'commodity name like oil or gold', 'score': 0.1547587662935257}]
Raw predictions for 'FAKE NEWS REPORTERS FROM CNN & THE NEW YORK TIMES SHOULD BE FIRED, IMMEDIATELY!!! BAD PEOPLE WITH EVIL INTENTIONS!!!': [{'start': 60, 'end': 113, 'text': 'FIRED, IMMEDIATELY!!! BAD PEOPLE WITH EVIL INTENTIONS', 'label': 'person name like Putin or Biden', 'score': 0.21465612947940826}]
Raw predictions for 'youtube.com/live/1_A-VBixOQk?s': [{'start': 0, 'end': 30, 'text': 'youtube.com/live/1_A-VBixOQk?s', 'label': 'person name like Putin or Biden', 'score': 0.07341241091489792}]
Raw predictions for 'The NATO Summit yesterday was GREAT, the most unified and productive in history. A wonderful day with incredible and caring Leaders. The Agreed to 5% gives NATO real power!': [{'start': 46, 'end': 112, 'text': 'unified and productive in history. A wonderful day with incredible', 'label': 'country name like Ukraine or China', 'score': 0.053172517567873}, {'start': 124, 'end': 160, 'text': 'Leaders. The Agreed to 5% gives NATO', 'label': 'person name like Putin or Biden', 'score': 0.29019686579704285}]
Raw predictions for 'youtube.com/live/Tio_tMsQdRw?s': [{'start': 0, 'end': 28, 'text': 'youtube.com/live/Tio_tMsQdRw', 'label': 'person name like Putin or Biden', 'score': 0.1129893809556961}]
Raw predictions for 'The cars and small trucks at the site were those of concrete workers trying to cover up the top of the shafts. Nothing was taken out of facility. Would take too long, too dangerous, and very heavy and...': [{'start': 13, 'end': 25, 'text': 'small trucks', 'label': 'country name like Ukraine or China', 'score': 0.060990188270807266}, {'start': 52, 'end': 109, 'text': 'concrete workers trying to cover up the top of the shafts', 'label': 'country name like Ukraine or China', 'score': 0.06856538355350494}, {'start': 111, 'end': 165, 'text': 'Nothing was taken out of facility. Would take too long', 'label': 'country name like Ukraine or China', 'score': 0.05519292131066322}, {'start': 167, 'end': 203, 'text': 'too dangerous, and very heavy and...', 'label': 'country name like Ukraine or China', 'score': 0.10392535477876663}]

In [82]:
df[["tweet_id", "tweet_text", "entities"]].head(5)

,tweet_id,tweet_text,entities
0,f6b6bc55c8b5,washingtonexaminer.com/restori,"[{'entity': 'washingtonexaminer.com/restori', ..."
1,362a7010b3c1,breitbart.com/politics/2025/06,"[{'entity': 'breitbart.com/politics/2025/06', ..."
2,65c19d0b7fb5,redstate.com/redstate-guest-ed,"[{'entity': 'redstate.com/redstate-guest-ed', ..."
3,8f0d572a979f,foxnews.com/opinion/loeffler-t,"[{'entity': 'foxnews.com/opinion/loeffler-t', ..."
4,707c1b8d12dd,nypost.com/2025/06/28/us-news/,"[{'entity': 'nypost.com/2025/06/28/us-news/', ..."

In [83]:
flat_entities = []

for _, row in df.iterrows():
    for ent in row["entities"]:
        flat_entities.append({
            "tweet_id": row["tweet_id"],
            "entity": ent["entity"].lower(),
            "label": ent["label"],
            "score": ent["score"]
        })

ner_df = pd.DataFrame(flat_entities)
ner_df.head(10)
ner_df

,tweet_id,entity,label,score
0,f6b6bc55c8b5,washingtonexaminer.com/restori,commodity name like oil or gold,0.132
1,362a7010b3c1,breitbart.com/politics/2025/06,person name like Putin or Biden,0.135
2,65c19d0b7fb5,redstate.com/redstate-guest-ed,commodity name like oil or gold,0.135
3,8f0d572a979f,foxnews.com/opinion/loeffler-t,person name like Putin or Biden,0.117
4,707c1b8d12dd,nypost.com/2025/06/28/us-news/,person name like Putin or Biden,0.132
...,...,...,...,...
505,fadeaf1d77b4,unyielding strength,commodity name like oil or gold,0.054
506,fadeaf1d77b4,"overwhelming force. time and again, our enemi...",organization name like Fed or OPEC,0.179
507,7a1386297599,youtube.com/live/447wkxyiijc?s,person name like Putin or Biden,0.137
508,68c3cb276bab,brad little is the strong and highly popular g...,commodity name like oil or gold,0.118
509,68c3cb276bab,"won big in 2016, 2020, and 2024",person name like Putin or Biden,0.169

In [84]:
ner_df.groupby(["label", "entity"]) \
      .size() \
      .sort_values(ascending=False) \
      .head(30)

label                               entity
country name like Ukraine or China  iran                                                               9
                                    los angeles                                                        5
person name like Putin or Biden     donald j. trump, president of the united states                    3
commodity name like oil or gold     u.s. senate                                                        2
                                    democrats                                                          2
                                    u.s. army                                                          2
                                    administration                                                     2
country name like Ukraine or China  canada                                                             2
commodity name like oil or gold     fed                                                                2
                                    united states                                                      2
organization name like Fed or OPEC  national guard                                                     2
country name like Ukraine or China  israel and iran                                                    2
commodity name like oil or gold     china                                                              2
organization name like Fed or OPEC  republicans                                                        2
person name like Putin or Biden     luck. i’ll see you all in d.c                                      2
organization name like Fed or OPEC  pride—because you are the righteous sword of american justice      1
                                    peace talks                                                        1
                                    parliamentarian), should not be allowed to hurt the republicans    1
                                    overwhelming force. time and again, our enemi...                   1
                                    remember, you still have to get reelected                          1
                                    republican                                                         1
                                    u.s. army                                                          1
                                    u.s., also. it was my great honor                                  1
                                    rapists, murderers, and terrorists. this tsunami                   1
                                    operation. in a certain and very ironic way, that perfect          1
                                    one of the easiest, yet most prestigious, jobs in america          1
                                    oil from iran                                                      1
                                    united states army. but for the american people                    1
                                    not for now. but we don’t want missiles                            1
                                    news conferences                                                   1
dtype: int64